on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
                cd /home/ubuntu/opt/laravel/kotak
                git pull
                php artisan cache:clear
                php artisan config:clear
                php artisan view:clear
                php artisan route:clear
                
